

clc
clear all 
close all 


nodeList = ["001e0610c429","001e0610c42e","001e0610c5fa",...
            "001e0610c2ed","001e0610c2d7","001e0610c06b",...
            "001e0610c2df","001e0610c6f4","001e0610c2e5"]

dataFolder = "../../../data" 
timeUnit=20;
% 

%% For PM 1 
estimator   = "PM1" ;
variable    = "opc_n2_pm1";
yLabel      = "Alpha Sense PM1";
titlePre    = "Training Data Set Combined ";
nodeSet     = "DFW";
saveNamePre = "PM1";


combinedTimePlotter(                                  nodeList,...
                                                       dataFolder,...
                                                       timeUnit,...
                                                       estimator,...
                                                       variable,...
                                                       yLabel,...
                                                       titlePre,...
                                                       nodeSet,...
                                                       saveNamePre...
                                                       )

%% For PM 2.5  
                                                   
estimator   = "PM2.5" ;
variable    = "opc_n2_pm2_5";
yLabel      = "Alpha Sense PM2.5";
titlePre    = "Training Data Set Combined ";
nodeSet     = "DFW";
saveNamePre = "PM2_5";


combinedTimePlotter(                                  nodeList,...
                                                       dataFolder,...
                                                       timeUnit,...
                                                       estimator,...
                                                       variable,...
                                                       yLabel,...
                                                       titlePre,...
                                                       nodeSet,...
                                                       saveNamePre...
                                                       )                                                   
                                                   
                                                   
%% For PM 10                                                

estimator   = "PM10" ;
variable    = "opc_n2_pm10";
yLabel      = "Alpha Sense PM10";
titlePre    = "Training Data Set Combined ";
nodeSet     = "DFW";
saveNamePre = "PM10";


combinedTimePlotter(                                  nodeList,...
                                                       dataFolder,...
                                                       timeUnit,...
                                                       estimator,...
                                                       variable,...
                                                       yLabel,...
                                                       titlePre,...
                                                       nodeSet,...
                                                       saveNamePre...
                                                       )
                                                   
                                                   
                                                   
                                                   
                                                   
                                                   
   

