
clc
clear all 
close all 


%% loading the Data 
tStart = datetime(2018,09,1);
tEnd   = datetime(2018,09,1);


nodeID = '001e0610c040';

load(strcat('../../../data/trainingData/',nodeID,'CalibrationData.mat'))
inputFormat = trainingDataReduced(:,7:47);

%% With Just the Bins  

trainingDataNow = pm2_5Bins(trainingDataReduced);
% PM 2.5
modelFun = @(b,x)b(1)*x(:,1)+b(2)*x(:,2)+ b(3)*x(:,3)+ b(4)*x(:,4);          
InitialEstimate = [1 1 1 1];
mdlPm2_5Bins = fitnlm(trainingDataNow,modelFun,InitialEstimate)
pm2_5PredictionwithBins = pm2_5PredictionBins(mdlPm2_5Bins,inputFormat);
% 
% 
% %% Bins+Alpha Sensor Value 
% 
% trainingDataNow = pm2_5BinsAlpha(trainingDataReduced);
% % PM 2.5
% modelFun = @(b,x)b(1)*x(:,1)+ b(2)*x(:,2)+ b(3)*x(:,3)+ b(4)*x(:,4)+ b(5)*x(:,5);          
% InitialEstimate = [1 1 1 1 1];
% mdlPm2_5BinsAlpha = fitnlm(trainingDataNow,modelFun,InitialEstimate)
% pm2_5PredictionwithBinsAlpha = pm2_5PredictionBinsAlpha(mdlPm2_5BinsAlpha,inputFormat);
% 
% 
% %% Bins+Alpha+Weather Sensor Value 
% 
% trainingDataNow = pm2_5BinsAlphaWeather(trainingDataReduced);
% % PM 2.5
% modelFun = @(b,x)b(1)*x(:,1)+ b(2)*x(:,2)+ b(3)*x(:,3)+ b(4)*x(:,4)+ b(5)*x(:,5)+ b(6)*x(:,6)+ b(7)*x(:,7)+ b(8)*x(:,8);          
% InitialEstimate = [1 1 1 1 1 1 1 1];
% mdlPm2_5BinsAlphaWeather        = fitnlm(trainingDataNow,modelFun,InitialEstimate)
% pm2_5PredictionwithBinsAlphaWeather = pm2_5PredictionBinsAlphaWeather(mdlPm2_5BinsAlphaWeather,inputFormat);
% 
% 
% 
% %% Get Ugly Node Data 
% 
% uglyNodeData          = properTable(getUglyNodeData(tStart,tEnd,nodeID));
% currentPredictionBins = pm2_5PredictionBins(mdlPm2_5Bins,uglyNodeData);
% currentPredictionBinsAlpha = pm2_5PredictionBinsAlpha(mdlPm2_5BinsAlpha,uglyNodeData);
% currentPredictionBinsAlphaWeather = pm2_5PredictionBinsAlphaWeather(mdlPm2_5BinsAlphaWeather,uglyNodeData);
% 
% 
% 
% %% Plotting Graphs for the Training Data 
% 
% 
% scatterPlotter(trainingDataReduced.pm2_5_Spectrometor,...
%                              trainingDataReduced.opc_n2_pm2_5,...
%                              50,...
%                              50,...
%                              'Spectrometor',....
%                              'Alpha Sensor',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Uncalibrated Data ',...
%                              'UncalibratedDataReduced')                            
%                          
% 
% 
%  scatterPlotter(trainingDataReduced.pm2_5_Spectrometor,...
%                              pm2_5PredictionwithBins,...
%                              50,...
%                              50,...
%                              'Spectrometor',....
%                              'Alpha Sensor',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Training Data Prediction with Bins',...
%                              'TrainingDataPredictionwithBinsReduced')                         
%                          
% 
% scatterPlotter(trainingDataReduced.pm2_5_Spectrometor,...
%                              pm2_5PredictionwithBinsAlpha,...
%                              50,...
%                              50,...
%                              'Spectrometor',....
%                              'Alpha Sensor',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Training Data Prediction with Bins and Alpha Sensor Reading',...
%                              'TrainingDataPredictionwithBinsAlphaSensorReadingReduced')  
% 
%                          
%        
% scatterPlotter(trainingDataReduced.pm2_5_Spectrometor,...
%                              pm2_5PredictionwithBinsAlphaWeather,...
%                              50,...
%                              50,...
%                              'Spectrometor',....
%                              'Alpha Sensor',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Training Data Prediction with Bins, Alpha Sensor Reading and Weather Data' ,...
%                              'TrainingDataPredictionwithBinsAlphaSensorReadingWeatherDataReduced')  
%                                             
% scatterPlotter(uglyNodeData.opc_n2_pm2_5,...
%                              currentPredictionBins,...
%                              50,...
%                              50,...
%                              'Alpha Sensor',....
%                              'Prediction',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Prediction with Bins ',...
%                              'PredcitionWithBinsReduced')
%                        
%                          
%  scatterPlotter(uglyNodeData.opc_n2_pm2_5,...
%                              currentPredictionBinsAlpha,...
%                              50,...
%                              50,...
%                              'Alpha Sensor',....
%                              'Prediction',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Prediction with Bins and Alpha Sensor Reading ',...
%                              'PredcitionWithBinsAlphaReduced')
%                                               
% scatterPlotter(uglyNodeData.opc_n2_pm2_5,...
%                              currentPredictionBinsAlphaWeather,...
%                              50,...
%                              50,...
%                              'Alpha Sensor',....
%                              'Prediction',...
%                              nodeID,...
%                              'pm2.5',....
%                              'Prediction with Bins, Alpha Sensor Reading and Weather Data ',...
%                              'PredcitionWithBinsAlphaSensorReadingAndWeatherDataReduced')                     
%                           
% timePlotter(trainingDataReduced.dateTime,...
%     trainingDataReduced.opc_n2_pm2_5,...
%     'Alpha Sensor',nodeID,'pm2.5', 'Uncalibrated Data ',...
%                              'UncalibratedReduced')
%                          
%                          
% %% 
% timePlotter2x(...
%     trainingDataReduced.dateTime ,...
%     trainingDataReduced.pm2_5_Spectrometor,...
%     trainingDataReduced.opc_n2_pm2_5,...
%     'pm2.5',...
%     'Spectrometor',...
%     'Alpha Sensor',...
%     nodeID,...
%     'pm2.5',...
%     'Uncalibrated Data',...
%     'UncalibratedDataReduced')
%                          
% 
% timePlotter3x(...
%     uglyNodeData.dateTime,...
%     currentPredictionBins,...
%     currentPredictionBinsAlpha,...
%     currentPredictionBinsAlphaWeather,...
%     'pm2.5',...
%     'Prediction with Bins',...
%     'Prediction with Bins and Alpha Sensor Reading',...
%     'Prediction with Bins, Alpha Sensor Reading and Weather Data',...
%     nodeID,...
%     'pm2.5',...
%     'Linear Regression Calibration ',...
%     'LinearRegressionCalibrationReduced'...
%     )
% 
% 
% timePlotter(trainingDataReduced.dateTime,trainingDataReduced.htu21d_humidity,...
%            'Humidity',...
%             nodeID,...
%             'Humidity',...
%             'Training Data',...
%             'HumidityRangeForTrainingDataReduced')
% 
% 
% timePlotter(uglyNodeData.dateTime,uglyNodeData.htu21d_humidity,...
%            'Humidity',...
%             nodeID,...
%             'Humidity',...
%             'Current Data',...
%             'HumidityRangeForCurrentDataReduced')
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
% 
