
clc
clear all
close all 

dataFolder = "../../../data"; 
tStart = datetime(2018,10,18);
tEnd   = datetime(2018,10,20);

nodeID =  "001e0610c2e5"


uglyNodeData        = getUglyNodeData(tStart,tEnd,nodeID);
uglyNodeDataPredict = tableMixerUglyNode(uglyNodeData);




predictorPM2_5 = predictorLoader(nodeID,dataFolder,"pm2_5","BoostedTree");


[inputWanted,variableNames]  =   getInputAll(uglyNodeDataPredict);

predictionCurrent         = predictorPM2_5.predict(inputWanted);

scatterPlotter1x(...
            uglyNodeDataPredict.opc_n2_pm2_5,...
            predictionCurrent,...
            50,50,...
            "Alpha Sensor",...
            "Boosted Tree Prediction",...
            nodeID,...
            "PM2.5",...
            "Feild Data - All Inputs",...
            "FeildData2_5AllInputs",...
            dataFolder);

% timePlotter2x(times,Data1,Data2,yLabel,duglyNodeData(isnan(table2array(uglyNodeData(:,1))),:)=[];isplayName1,displayName2,nodeID,estimator,titlePre,saveNamePre)
timePlotter2x(...
    uglyNodeDataPredict.dateTime,...
    uglyNodeDataPredict.opc_n2_pm2_5,...
    predictionCurrent,...
    "PM2.5",...
    "Alpha Sensor",...
    "Booster Tree Prediction",...
     nodeID,...
     "PM2.5",...
     "Boosted Tree Prediction Comparison - Feild Data - All Inputs",... 
     "FieldDataCompPM2_5AllInputs");









