% 
% clc 
% clear all 
close all 
% 
nodeID     = "001e0610c2e5";
dataFolder = "../../../data"; 

trainingData  = loadUglyNodeTraining(nodeID,dataFolder,20);

[trainTable,valTable,testTable] = trainTestSplitTable(trainingData,.7,0,.3);

[trainingInput,variableLabels] = getInputOPC(trainTable);
[testingInput,variableLabels] = getInputOPC(testTable);

loopLabels = ["PM1","PM2.5","PM10"  ]
loopNames  = [ "pm1","pm2_5","pm10"]

for loopIndex = 1:length(loopNames)
    
eval(strcat("trainingTarget = trainTable.",loopNames(loopIndex),"_Spectrometor;"));  
eval(strcat("testingTarget  = testTable.",loopNames(loopIndex),"_Spectrometor;"));  


%% Training Data 

Mdl=fitrensemble(...
   	trainingInput,...
    trainingTarget,...
'OptimizeHyperparameters','all',...
'HyperparameterOptimizationOptions',...
struct('UseParallel',true,'ShowPlots',true));


eval(strcat('dataSaver(nodeID,"',loopNames(loopIndex),'BoostedTreeOPC","Mdl","predictors",Mdl);'));


% Getiing the Prediction 
trainingPrediction  = predict(Mdl,trainingInput)';
testingPrediction   = predict(Mdl,testingInput)';
 
% Having the Importaince 
predictorImportaince = predictorImportance(Mdl);
 

% plotImportaince(predictorImportaince,variableLabels,nodeID,estimator,titlePost,saveNamePre,dataFolder)

plotImportaince(...
    predictorImportaince,...
    variableLabels,...
    nodeID,...
    loopLabels(loopIndex),...
    "Using OPC Inputs",...
    strcat(loopNames(loopIndex),"OPCInputs"),...
    dataFolder)

 
scatterPlotter1x(...
     trainingTarget,...
     trainingPrediction',...
     1000,...
     1000,...
     "Grimm Sensor",...
     "Alpha Sensor",...
     nodeID, ...
     loopLabels(loopIndex),...
     "Boosted Tree Prediction - Training - OPC Inputs",...
     strcat(loopNames(loopIndex),"BoostedTreeTrainingOPCInputs"),...
     dataFolder);



scatterPlotter1x(...
     testingTarget,...
     testingPrediction',...
     1000,...
     1000,...
     "Grimm Sensor",...
     "Alpha Sensor",...
     nodeID, ...
     loopLabels(loopIndex),...
     "Boosted Tree Prediction - Testing - OPC Inputs",...
     strcat(loopNames(loopIndex),"BoostedTreeTestingOPCInputs"),...
     dataFolder);

 
 
end
