
clc
clear all
close all 

dataFolder = "../../../data"; 
tStart = datetime(2018,10,1);
tEnd   = datetime(2018,10,20);

nodeID =  "001e0610c2e5"

uglyNodeData        = getUglyNodeData(tStart,tEnd,nodeID);
uglyNodeDataPredict = tableMixerUglyNode(uglyNodeData);

uglyNodeDataPredict(uglyNodeDataPredict.opc_n2_pm2_5>1000,:)=[];


predictorPM2_5 = predictorLoader(nodeID,dataFolder,"pm2_5","BoostedTreeOPC")

[inputWanted,variableNames]  =   getInputOPC(uglyNodeDataPredict);

predictionCurrent            =    predictorPM2_5.predict(inputWanted);

scatterPlotter1x(...
            uglyNodeDataPredict.opc_n2_pm2_5,...
            predictionCurrent,...
            50,50,...
            "Alpha Sensor",...
            "Boosted Tree Prediction",...
            nodeID,...
            "PM2.5",...
            "Feild Data - OPC Inputs",...
            "FeildDataOPCInputsPM2_5",...
            dataFolder)
        
timePlotter2x(...
    uglyNodeDataPredict.dateTime,...
    uglyNodeDataPredict.opc_n2_pm2_5,...
    predictionCurrent,...
    "PM2.5",...
    "Alpha Sensor",...
    "Booster Tree Prediction",...
     nodeID,...
     "PM2.5",...
     "Boosted Tree Prediction Comparison - Feild Data - OPC Inputs",... 
     "FieldDataCompPM2_5")


