function [nodeData] = csvToDotMat(nodeNum,beehiveID)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    A:\Coding\Tenessee\001e0610c040.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/10/03 15:19:14

%% Initialize variables.
filename = strcat(pwd,"\Tenessee\",beehiveID,".csv");
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: categorical (%C)
%   column3: categorical (%C)
%	column4: categorical (%C)
%   column5: categorical (%C)
%	column6: categorical (%C)
%   column7: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%C%C%C%C%C%C%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
nodeData = table(dataArray{1:end-1}, 'VariableNames', {'timestamp','node_id','subsystem','sensor','parameter','value_raw','value_hrf'});

nodeData.node_id   = [] ;
nodeData.subsystem = [] ;
nodeData.value_raw = [] ; 
nodeData.sensor = strcat(string(nodeData.sensor),"_",string(nodeData.parameter));
nodeData.parameter=[];

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;
end

