function pmOut = binsOnlyPM2_5(CalibrationData)

pmOut = table(...
              CalibrationData.opc_n2_bin0,...
              CalibrationData.opc_n2_bin1,...
              CalibrationData.opc_n2_bin2,...
              CalibrationData.opc_n2_bin3...
                );
            
            
pmOut.Properties.VariableNames = [ {'opc_n2_bin0'}, ...
                                     {'opc_n2_bin1'}, ...
                                     {'opc_n2_bin2'}, ...
                                     {'opc_n2_bin3'} ...
                                     ];
end
