function pm1Out = binsAndPM1(CalibrationData)

pm1Out = table(...
              CalibrationData.opc_n2_bin0,...
              CalibrationData.opc_n2_bin1,...
              CalibrationData.pm1_Spectrometor...
                );
            
            
pm1Out.Properties.VariableNames = [ {'opc_n2_bin0'}, ...
                                    {'opc_n2_bin1'}, ...
                                    {'pm1_Spectrometor'} ];
end
