function pm1Out = binsOnlyPM1(CalibrationData)

pm1Out = table(...
              CalibrationData.opc_n2_bin0,...
              CalibrationData.opc_n2_bin1...
                );
            
            
pm1Out.Properties.VariableNames = [ {'opc_n2_bin0'}, ...
                                    {'opc_n2_bin1'} ...
                                   ];
end
