function [] = combinedTimePlotter(                     nodeList,...
                                                       dataFolder,...
                                                       timeUnit,...
                                                       estimator,...
                                                       variable,...
                                                       yLabel,...
                                                       titlePre,...
                                                       nodeSet,...
                                                       saveNamePre...
                                                       )
colorCodes =  { [128, 0, 0]/255 ,...
                [255, 255, 0]/255,...
                [128, 128, 0]/255 ,...
                [0, 255, 0]/255,...
                [0, 128, 0]/255,...
                [0, 255, 255]/255,...
                [0, 128, 128]/255,...
                [0, 0, 255]/255,...
                [0, 0, 128]/255,...
                [255, 0, 255]/255,...
                [128, 0, 128]/255 ...
                    };



 figureAll = figure(...
    'NumberTitle','off',...
    'units','normalized','outerposition',[0 0 1 1],...
    'Visible','off');

for nodeIndex =1:length(nodeList)
     
nodeID = nodeList(nodeIndex)
 
trainingData = loadUglyNodeTraining(nodeID,dataFolder,timeUnit);
   
  
times = trainingData.dateTime;


eval(strcat("Data = trainingData.",variable,";"));

plot1= plot(...
        times, ...
        Data,'.');
% 'Marker','o',...
% 'LineStyle','none',...
set(...
plot1,...
'DisplayName',nodeID,...    
'Color', colorCodes{nodeIndex});

hold on



end

yl=strcat(yLabel);
ylabel(yl,'FontWeight','bold','FontSize',20);

% Create xlabel
xlabel('Time','FontWeight','bold','FontSize',22);

% Create title
tl= string(titlePre) +  newline + ...
     strcat(nodeSet,...
    " (",...
    estimator,...
    ")");

% % Create legend
legend1 = legend('show');
set(legend1,'Location','northwest');
% 
title(tl,'FontWeight','bold','FontSize',22);


Fig_name = strcat('../../../data/plots/',nodeSet ,'/',saveNamePre,nodeSet ,...
           'Combined.jpg');
createDirectory(Fig_name);
saveas(figureAll,char(Fig_name));

Fig_name = strcat('../../../data/plots/',nodeSet ,'/',saveNamePre,nodeSet ,...
           'Combined.fig');
createDirectory(Fig_name);
saveas(figureAll,char(Fig_name));
close all 

end

