function [inputWanted ,variableLabels] = getInputOPC(tableIn)
inputWanted =  [ tableIn.opc_n2_bin0,...
                   tableIn.opc_n2_bin1,...
                   tableIn.opc_n2_bin2,...
                   tableIn.opc_n2_bin3,...
                   tableIn.opc_n2_bin4,...
                   tableIn.opc_n2_bin5,...
                   tableIn.opc_n2_bin6,...
                   tableIn.opc_n2_bin7,...
                   tableIn.opc_n2_bin8,...
                   tableIn.opc_n2_bin9,...
                   tableIn.opc_n2_bin10,...
                   tableIn.opc_n2_bin11,...
                   tableIn.opc_n2_bin12,...
                   tableIn.opc_n2_bin13,...
                   tableIn.opc_n2_bin14,...
                   tableIn.opc_n2_bin15,...
                   tableIn.opc_n2_pm1,...
                   tableIn.opc_n2_pm2_5,...
                   tableIn.opc_n2_pm10...
];
               
               
               
variableLabels =  [         "Bin 0",...
                            "Bin 1",...
                            "Bin 2",...
                            "Bin 3",...
                            "Bin 4",...
                            "Bin 5",...
                            "Bin 6",...
                            "Bin 7",...
                            "Bin 8",...
                            "Bin 9",...
                            "Bin 10",...
                            "Bin 11",...
                            "Bin 12",...
                            "Bin 13",...
                            "Bin 14",...
                            "Bin 15",...
                            "PM 1",...
                            "PM 2.5",...
                            "PM 10"...
                            ];
               
end

